# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171127_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approveed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
