# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20171127_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='approveed',
            new_name='approved',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
